name: Create Release for all PDK Projects
permissions:
  actions: write
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'Owner of the repository (e.g. mdsol)'
        required: true
        default: 'mdsol'

      base_branch:
        description: 'Base branch to check out (e.g. develop)'
        required: true
        default: 'develop'
        
      jira_ticket:
        description: 'Jira ticket number (e.g. MDSO-19142)'
        required: true
        default: 'MDSO-19744'

      dry_run:
        description: 'Dry Run (will not trigger a release, but will show the commands)'
        required: true
        type: boolean
        default: true

jobs:
  All_PDK_Projects:
    runs-on: ubuntu-latest
    
    env:
      GH_TOKEN: ${{ secrets.PDK_DEVOPS_PAT }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Install the 'requests' module

    - name: Run script
      run: | 
        python tag_and_branch_releases_for_products.py \
        -owner "${{ github.event.inputs.owner }}" \
        -base_branch "${{ github.event.inputs.base_branch }}" \
        -jira_ticket "${{ github.event.inputs.jira_ticket }}" \
        -dry_run "${{ github.event.inputs.dry_run }}"
      working-directory: scripts/release_management
